# Generated by Django 4.1.7 on 2025-04-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_abc_app', '0021_alter_abcmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abcmodel',
            options={'ordering': ['-id'], 'verbose_name': 'Расчёт Z', 'verbose_name_plural': 'Расчёты Z'},
        ),
        migrations.RemoveField(
            model_name='abcmodel',
            name='a',
        ),
        migrations.RemoveField(
            model_name='abcmodel',
            name='b',
        ),
        migrations.RemoveField(
            model_name='abcmodel',
            name='c',
        ),
        migrations.RemoveField(
            model_name='abcmodel',
            name='result',
        ),
        migrations.RemoveField(
            model_name='abcmodel',
            name='task',
        ),
        migrations.AddField(
            model_name='abcmodel',
            name='x',
            field=models.FloatField(default=0.0, verbose_name='X'),
        ),
        migrations.AddField(
            model_name='abcmodel',
            name='y',
            field=models.FloatField(default=0.0, verbose_name='Y'),
        ),
        migrations.AddField(
            model_name='abcmodel',
            name='z',
            field=models.FloatField(default=0.0, verbose_name='Z'),
        ),
        migrations.AlterField(
            model_name='abcmodel',
            name='current_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
