# Generated by Django 4.1.7 on 2025-04-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_abc_app', '0022_alter_abcmodel_options_remove_abcmodel_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('admission_year', models.PositiveIntegerField(verbose_name='Год поступления')),
                ('program_name', models.CharField(max_length=255, verbose_name='Название ОП')),
                ('date_submitted', models.DateTimeField(auto_now_add=True, verbose_name='Дата заполнения')),
            ],
        ),
        migrations.DeleteModel(
            name='AbcModel',
        ),
    ]
